name: Update ECS Task Definition Action
description: Updates an ECS task definition with single or multiple containers, replacing their image references.
author: YUMEMI Inc.
branding:
  icon: refresh-ccw
  color: orange
runs:
  using: node16
  main: 'index.js'
inputs:
  family:
    required: true
    description: Name of the task definition family to where fetch the latest revision and create a new revision.
  images:
    required: true
    description: Map of the container name and the image URI to update in the task definition. Must be `container_name=image_uri` format.
